### PR TITLE
Oh hai

### PR DESCRIPTION
**Pull request by garbles**
Added bootstrap-responsive CSS, as well as stylus.

Stylus is essentially SASS for Node applications since the syntax is exactly the same.

Also added a "navbar" on the side so that it's easier to switch between conversations rather than having to click back every time, but there's probably a more elegant way to do it. How do you do partials in Meteor? And then partial-specific template commands in client.js??

### CODE REVIEW

**Comment by garbles** [comment]
I'll probably spend the rest of the day making this thing look nice.

**Comment by brentvatne** [comment]
> Also added a "navbar" on the side so that it's easier to switch between conversations rather than having to click back every time, but there's probably a more elegant way to do it. How do you do partials in Meteor? And then partial-specific template commands in client.js??

I think this is with {{> TemplateName}}

**Comment by brentvatne** [comment]
No need to close this, we haven't merged it in yet

**Comment by brentvatne** [comment]
Now it's properly closed :P

**Pull request merged**
